### ISSUE TITLE
Seemingly random crashes.

### ISSUE THREAD

**Issue by DrekiDegga** [spesmilo/electrumx#162]
I keep getting a random crash. I'm posting the log output here but please let me know what else I can do to help. 

The loglevel is set to warn because I've found that at 'info' the log grows by gigabytes per day because every single connection gets logged. 

```
Jan 12 12:42:27 node electrumx_server[20416]: Exception in callback UVTransport._call_connection_made
Jan 12 12:42:27 node electrumx_server[20416]: handle: <Handle UVTransport._call_connection_made>
Jan 12 12:42:27 node electrumx_server[20416]: Traceback (most recent call last):
Jan 12 12:42:27 node electrumx_server[20416]:   File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
Jan 12 12:42:27 node electrumx_server[20416]:   File "uvloop/handles/tcp.pyx", line 155, in uvloop.loop.TCPTransport._call_connection_made
Jan 12 12:42:27 node electrumx_server[20416]:   File "uvloop/handles/basetransport.pyx", line 145, in uvloop.loop.UVBaseTransport._call_connection_made
Jan 12 12:42:27 node electrumx_server[20416]:   File "uvloop/handles/basetransport.pyx", line 142, in uvloop.loop.UVBaseTransport._call_connection_made
Jan 12 12:42:27 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/aiorpcx/rawsocket.py", line 80, in connection_made
Jan 12 12:42:27 node electrumx_server[20416]:     self._remote_address = NetAddress(peername[0], peername[1])
Jan 12 12:42:27 node electrumx_server[20416]: TypeError: 'NoneType' object is not subscriptable
Jan 12 12:42:29 node electrumx_server[20416]: ERROR:electrumx:ElectrumX server terminated abnormally
Jan 12 12:42:29 node electrumx_server[20416]:   File "/usr/local/bin/electrumx_server", line 35, in main
Jan 12 12:42:29 node electrumx_server[20416]: Traceback (most recent call last):
Jan 12 12:42:29 node electrumx_server[20416]:   File "/usr/local/bin/electrumx_server", line 35, in main
Jan 12 12:42:29 node electrumx_server[20416]:     asyncio.run(controller.run())
Jan 12 12:42:29 node electrumx_server[20416]:   File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
Jan 12 12:42:29 node electrumx_server[20416]:     return loop.run_until_complete(main)
Jan 12 12:42:29 node electrumx_server[20416]:   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/electrumx/lib/server_base.py", line 129, in run
Jan 12 12:42:29 node electrumx_server[20416]:     await server_task
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/electrumx/lib/server_base.py", line 102, in serve
Jan 12 12:42:29 node electrumx_server[20416]:     await self.serve(shutdown_event)
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/electrumx/server/controller.py", line 134, in serve
Jan 12 12:42:29 node electrumx_server[20416]:     await group.spawn(wait_for_catchup())
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 255, in __aexit__
Jan 12 12:42:29 node electrumx_server[20416]:     await self.join()
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 213, in join
Jan 12 12:42:29 node electrumx_server[20416]:     raise task.exception()
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/electrumx/server/mempool.py", line 366, in keep_synchronized
Jan 12 12:42:29 node electrumx_server[20416]:     await group.spawn(self._logging(synchronized_event))
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 255, in __aexit__
Jan 12 12:42:29 node electrumx_server[20416]:     await self.join()
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/aiorpcx/curio.py", line 213, in join
Jan 12 12:42:29 node electrumx_server[20416]:     raise task.exception()
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/electrumx/server/mempool.py", line 263, in _refresh_hashes
Jan 12 12:42:29 node electrumx_server[20416]:     await self.api.on_mempool(touched, height)
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/electrumx/server/controller.py", line 67, in on_mempool
Jan 12 12:42:29 node electrumx_server[20416]:     await self._maybe_notify()
Jan 12 12:42:29 node electrumx_server[20416]:   File "/home/electrumx/.local/lib/python3.8/site-packages/electrumx/server/controller.py", line 55, in _maybe_notify
Jan 12 12:42:29 node electrumx_server[20416]:     await self.notify(height, touched)
```

I believe the log I'm posting here is the start of the crash. I can post more log if needed or I can set loglevel to info for the next crash if this isn't enough information.

**Comment by SomberNight** [comment]
Root cause might be same as https://github.com/spesmilo/electrumx/issues/40

**Comment by SomberNight** [comment]
can you still reproduce this on current master?
