### ISSUE TITLE
ElectrumX crash of two instances simultaneously

### ISSUE THREAD

**Issue by yakitorifoodie** [spesmilo/electrumx#22]
Version : 1.15.0

I have two instances of electrumX running and both crashed at the same time with same log.
crash log:    https://paste.ubuntu.com/p/8fqJh93d95/

**Comment by yakitorifoodie** [comment]
same issue after a fresh install of electrumX. 

log : 

`INFO:Prefetcher:cancelled; prefetcher stopping 
INFO:BlockProcessor:flushing to DB for a clean shutdown...
INFO:Controller:shutting down
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.15.0-py3.7.egg/EGG-INFO/scripts/electrumx_server", line 35, in main
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.15.0-py3.7.egg/electrumx/lib/server_base.py", line 125, in run
    await server_task
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.15.0-py3.7.egg/electrumx/lib/server_base.py", line 98, in serve
    await self.serve(shutdown_event)
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/session.py", line 621, in serve
    await group.spawn(self._manage_servers())
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/peers.py", line 459, in discover_peers
    await group.spawn(self._import_peers())
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/peers.py", line 234, in _monitor_peer
    if await self._should_drop_peer(peer):
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/peers.py", line 277, in _should_drop_peer
    await self._verify_peer(session, peer)
  File "/usr/local/lib/python3.7/dist-packages/electrumX-1.15.0-py3.7.egg/electrumx/server/peers.py", line 383, in _verify_peer
    await session.send_request('server.add_peer', [features])
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/session.py", line 529, in send_request
    return await self._send_concurrent(message, future, 1)
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/session.py", line 499, in _send_concurrent
    return await future
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/jsonrpc.py", line 721, in receive_message
    item, request_id = self._protocol.message_to_item(message)
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/jsonrpc.py", line 273, in message_to_item
    return cls._process_response(payload)
  File "/usr/local/lib/python3.7/dist-packages/aiorpcX-0.18.4-py3.7.egg/aiorpcx/jsonrpc.py", line 220, in _process_response
    raise cls._error(code, message, False, request_id)
aiorpcx.jsonrpc.ProtocolError: (-32600, 'ill-formed response error object: no new valid entries')
/usr/local/lib/python3.7/dist-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py:977: RuntimeWarning: coroutine 'noop' was never awaited
  self._resp.release()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.7/dist-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py:518: RuntimeWarning: coroutine 'noop' was never awaited
  resp.release()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.7/dist-packages/aiohttp-4.0.0a1-py3.7-linux-x86_64.egg/aiohttp/client.py:541: RuntimeWarning: coroutine 'noop' was never awaited
  resp.release()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f3713dd94d0>
transport: <_SelectorSocketTransport closing fd=30>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 860, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/sslproto.py", line 680, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 864, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 673, in _fatal_error
    self._force_close(exc)
  File "/usr/lib/python3.7/asyncio/selector_events.py", line 685, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 683, in call_soon
    self._check_closed()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 475, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed


`
