### ISSUE TITLE
TypeError: '<' not supported between instances of 'UTXO' and 'UTXO'

### ISSUE THREAD

**Issue by SomberNight** [spesmilo/electrumx#23]
On master:
```
2020-06-19T17:35:01.902288380Z ERROR:ElectrumX:[110] exception handling Request('blockchain.scripthash.listunspent', ['bf5cba1ab27952ef2c119cab412adf0aafaa74ba395e6d974fab21b7a2961593'])
2020-06-19T17:35:01.902308915Z Traceback (most recent call last):
2020-06-19T17:35:01.902312317Z   File "/usr/local/lib/python3.8/site-packages/aiorpcx/session.py", line 467, in _throttled_request
2020-06-19T17:35:01.902315232Z     result = await self.handle_request(request)
2020-06-19T17:35:01.902318482Z   File "/usr/local/lib/python3.8/site-packages/electrumx/server/session.py", line 889, in handle_request
2020-06-19T17:35:01.902321465Z     return await coro
2020-06-19T17:35:01.902323689Z   File "/usr/local/lib/python3.8/site-packages/electrumx/server/session.py", line 1119, in scripthash_listunspent
2020-06-19T17:35:01.902326238Z     return await self.hashX_listunspent(hashX)
2020-06-19T17:35:01.902328657Z   File "/usr/local/lib/python3.8/site-packages/electrumx/server/session.py", line 1059, in hashX_listunspent
2020-06-19T17:35:01.902330992Z     utxos = sorted(utxos)
2020-06-19T17:35:01.902333032Z TypeError: '<' not supported between instances of 'UTXO' and 'UTXO'
```

**Comment by SomberNight** [comment]
Regression from https://github.com/spesmilo/electrumx/commit/31ef8873f8c24995e50f024670610869f17385a0

**Comment by JustinTArthur** [comment]
Thanks for the fix. Sorry for not catching this!
