### ISSUE TITLE
Server crash: AttributeError: 'NoneType' object has no attribute 'fail'

### ISSUE THREAD

**Issue by whizz** [spesmilo/electrumx#40]
After several days of operation, the server crashed. I was running master on commit 10616105b9ca2fc013dd3b0efbc46db7e847a382. Looking at the logs, might also be a problem in aiorpcX.

Log output follows:

```
INFO:PeerManager:[ns3079944.ip-217-182-196.eu:50002 SSL] [Errno 104] Connection reset by peer
INFO:PeerManager:[ns3079944.ip-217-182-196.eu:50002 SSL] [Errno -5] No address associated with hostname
Exception in callback RSTransport.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle RSTransport.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/rawsocket.py", line 80, in connection_made
    self._remote_address = NetAddress(peername[0], peername[1])
TypeError: 'NoneType' object is not subscriptable
Exception in callback _SelectorSocketTransport._call_connection_lost(ConnectionRes...eset by peer'))
handle: <Handle _SelectorSocketTransport._call_connection_lost(ConnectionRes...eset by peer'))>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 968, in _call_connection_lost
    super()._call_connection_lost(exc)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 726, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/rawsocket.py", line 94, in connection_lost
    self._framer.fail(ConnectionLostError())
AttributeError: 'NoneType' object has no attribute 'fail'
```
...
```
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/EGG-INFO/scripts/electrumx_server", line 35, in main
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/server_base.py", line 125, in run
    await server_task
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/lib/server_base.py", line 98, in serve
    await self.serve(shutdown_event)
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/mempool.py", line 335, in keep_synchronized
    await group.spawn(self._logging(synchronized_event))
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/mempool.py", line 232, in _refresh_hashes
    await self.api.on_mempool(touched, height)
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/controller.py", line 67, in on_mempool
    await self._maybe_notify()
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/controller.py", line 55, in _maybe_notify
    await self.notify(height, touched)
  File "/usr/local/lib/python3.8/dist-packages/electrumX-1.15.0-py3.8.egg/electrumx/server/session.py", line 766, in _notify_sessions
    await self._task_group.spawn(session.notify, touched, height_changed)
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 148, in spawn
    self._add_task(task)
  File "/usr/local/lib/python3.8/dist-packages/aiorpcX-0.18.4-py3.8.egg/aiorpcx/curio.py", line 123, in _add_task
    raise RuntimeError('task group is closed')
RuntimeError: task group is closed
```

**Comment by SomberNight** [comment]
https://github.com/kyuupichan/aiorpcX/blob/bd2185aaeb7cd8b18e24866c4a04387650ff4834/aiorpcx/rawsocket.py#L79

As per python docs, `connection_made` is called [once there is a successful connection](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseProtocol.connection_made), 
re `transport.get_extra_info('peername')`, [docs say](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.get_extra_info):
> 'peername': the remote address to which the socket is connected, result of socket.socket.getpeername() (None on error)

Not sure what the "error" is if there was a succesful connection... but clearly this case should be handled somehow there.

-----

Are you sure the second traceback is related to the first? How much time passed between the two?

If they are related, then maybe via `_clear_stale_sessions`?
https://github.com/spesmilo/electrumx/blob/148df48fca633da0f1d8dcdf8e7f9c1cdcb392fb/electrumx/server/session.py#L243

**Comment by whizz** [comment]
> Are you sure the second traceback is related to the first?

Not sure :)

> How much time passed between the two?

They were immediately after. I just left out few lines with new connections being established.

**Comment by kyuupichan** [comment]
uvloop?

**Comment by mercurytoxic** [comment]
Same error, in my case uvloop is not being used. Running master on commit https://github.com/spesmilo/electrumx/commit/0e321d2195b0b1536f2ffeb6f9181f3e3d5b8b0a

electrumx.conf
...
`#    EVENT_LOOP_POLICY = uvloop`
...

```
Jan 06 22:42:43 bitcoin electrumx-server[4206]: Exception in callback RSTransport.connection_made(<_SelectorSoc...e, bufsize=0>>)                    
Jan 06 22:42:43 bitcoin electrumx-server[4206]: handle: <Handle RSTransport.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Jan 06 22:42:43 bitcoin electrumx-server[4206]: Traceback (most recent call last):                                                                                     
Jan 06 22:42:43 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run                                                                                                                                              
Jan 06 22:42:43 bitcoin electrumx-server[4206]:     self._context.run(self._callback, *self._args)                                 
Jan 06 22:42:43 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/aiorpcx/rawsocket.py", line 80, in connection_made
Jan 06 22:42:43 bitcoin electrumx-server[4206]:     self._remote_address = NetAddress(peername[0], peername[1])                                                                                                                                               
Jan 06 22:42:43 bitcoin electrumx-server[4206]: TypeError: 'NoneType' object is not subscriptable                                    
Jan 06 22:42:43 bitcoin electrumx-server[4206]: INFO:SessionManager:maximum sessions 300 reached, stopping new connections until count drops to 285
Jan 06 22:42:43 bitcoin electrumx-server[4206]: INFO:SessionManager:closing down server for ws://all_interfaces:50003
Jan 06 22:42:43 bitcoin electrumx-server[4206]: INFO:SessionManager:closing down server for tcp://all_interfaces:50001
Jan 06 22:42:43 bitcoin electrumx-server[4206]: INFO:SessionManager:closing down server for wss://all_interfaces:50004                                                                                                                                        
Jan 06 22:42:43 bitcoin electrumx-server[4206]: INFO:SessionManager:closing down server for ssl://all_interfaces:50002                                                                                                                                        
Jan 06 22:42:43 bitcoin electrumx-server[4206]: Exception in callback _SelectorSocketTransport._call_connection_lost(ConnectionRes...eset by peer'))                                                                                                          
Jan 06 22:42:43 bitcoin electrumx-server[4206]: handle: <Handle _SelectorSocketTransport._call_connection_lost(ConnectionRes...eset by peer'))>                                                                                                               
Jan 06 22:42:43 bitcoin electrumx-server[4206]: Traceback (most recent call last):                                             
Jan 06 22:42:43 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run                                                                                                                                              
Jan 06 22:42:43 bitcoin electrumx-server[4206]:     self._context.run(self._callback, *self._args)                                                                                                                                                            
Jan 06 22:42:43 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/asyncio/selector_events.py", line 978, in _call_connection_lost                                                                                                                   
Jan 06 22:42:43 bitcoin electrumx-server[4206]:     super()._call_connection_lost(exc)                                                                                                                                                                        
Jan 06 22:42:43 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/asyncio/selector_events.py", line 736, in _call_connection_lost                                                                                                                   
Jan 06 22:42:43 bitcoin electrumx-server[4206]:     self._protocol.connection_lost(exc)                                                                                                                                                                       
Jan 06 22:42:43 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/aiorpcx/rawsocket.py", line 94, in connection_lost                                                                                                                  
Jan 06 22:42:43 bitcoin electrumx-server[4206]:     self._framer.fail(ConnectionLostError())                                                                                                                                                                  
Jan 06 22:42:43 bitcoin electrumx-server[4206]: AttributeError: 'NoneType' object has no attribute 'fail'                                                                                                                                                     
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:SessionManager:closing down server for rpc://localhost:8000                                                                                                                                              
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:ElectrumX:[6600950] disconnected whilst throttled                                                                                                                                                        
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:ElectrumX:[6609675] disconnected whilst throttled                                                                                                                                                        
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:ElectrumX:[6623079] disconnected whilst throttled                                                                                                                                                        
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:ElectrumX:[6632591] disconnected whilst throttled                                                                                                                                                        
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:ElectrumX:[6632948] disconnected whilst throttled                                                                                                                                                        
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:ElectrumX:[6634764] disconnected whilst throttled                                                                                                                                                        
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:ElectrumX:[6638102] disconnected whilst throttled                                                                                                                                                        
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:ElectrumX:[6080274] disconnected.  Sent 1,596,442 bytes in 495 messages                                                                                                                                  
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:Prefetcher:cancelled; prefetcher stopping                                                                                                                                                                
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:BlockProcessor:flushing to DB for a clean shutdown...                                                                                                                                                    
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:Controller:shutting down                                                  
Jan 06 22:42:44 bitcoin electrumx-server[4206]: INFO:Controller:shutdown complete                                              
Jan 06 22:42:44 bitcoin electrumx-server[4206]: ERROR:electrumx:ElectrumX server terminated abnormally                                                                                                                                                        
Jan 06 22:42:44 bitcoin electrumx-server[4206]: Traceback (most recent call last):                                             
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/bin/electrumx-server", line 35, in main                                                                                                                                                          
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     asyncio.run(controller.run())                                              
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run                                                                                                                                              
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     return loop.run_until_complete(main)                                                                                                                                                                      
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete                                                                                                                          
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     return future.result()                                                     
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/electrumx/lib/server_base.py", line 129, in run                                                                                                                     
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     await server_task                                                          
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/electrumx/lib/server_base.py", line 102, in serve                                                                                                                   
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     await self.serve(shutdown_event)                                                                                                                                                                          
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/electrumx/server/controller.py", line 131, in serve                                                                                                                 
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     async with TaskGroup() as group:                                                                                                                                                                          
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/aiorpcx/curio.py", line 255, in __aexit__                                                                                                                           
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     await self.join()                                                          
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/aiorpcx/curio.py", line 213, in join                                                                                                                                
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     raise task.exception()                                                     
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/electrumx/server/mempool.py", line 363, in keep_synchronized                                                                                                        
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     async with TaskGroup() as group:                                                                                                                                                                          
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/aiorpcx/curio.py", line 255, in __aexit__                                                                                                                           
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     await self.join()                                                          
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/aiorpcx/curio.py", line 213, in join                                                                                                                                
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     raise task.exception()                                                     
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/electrumx/server/mempool.py", line 263, in _refresh_hashes                                                                                                          
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     await self.api.on_mempool(touched, height)                                                                                                                                                                
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/electrumx/server/controller.py", line 67, in on_mempool                                                                                                             
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     await self._maybe_notify()                                                 
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/electrumx/server/controller.py", line 55, in _maybe_notify                                                                                                          
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     await self.notify(height, touched)                                                                                                                                                                        
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 788, in _notify_sessions                                                                                                         
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     await self._task_group.spawn(session.notify, touched, height_changed)                                                                                                                                     
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/aiorpcx/curio.py", line 148, in spawn                                                                                                                               
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     self._add_task(task)                                                       
Jan 06 22:42:44 bitcoin electrumx-server[4206]:   File "/usr/lib/python3.10/site-packages/aiorpcx/curio.py", line 123, in _add_task                                                                                                                           
Jan 06 22:42:44 bitcoin electrumx-server[4206]:     raise RuntimeError('task group is closed')                                                                                                                                                                
Jan 06 22:42:44 bitcoin electrumx-server[4206]: RuntimeError: task group is closed                                             
Jan 06 22:42:47 bitcoin electrumx-rpc[877844]: cannot connect - is ElectrumX catching up, not running, or is 8000 the wrong RPC port?                                                                                                                         
Jan 06 22:42:47 bitcoin systemd[1]: electrumx.service: Control process exited, code=exited, status=1/FAILURE                                                                                                                                                  
Jan 06 22:42:47 bitcoin systemd[1]: electrumx.service: Failed with result 'exit-code'.                                                                                                                                                                        
Jan 06 22:42:47 bitcoin systemd[1]: electrumx.service: Consumed 13h 33min 24.660s CPU time. 
```

**Comment by SomberNight** [comment]
note: this is fixed in newer aiorpcx in https://github.com/kyuupichan/aiorpcX/commit/01a129917b6b483b804795060d3af3eed72b4c57

**Comment by mercurytoxic** [comment]
@SomberNight https://github.com/spesmilo/electrumx/blob/master/setup.py requires `'aiorpcX[ws]>=0.18.5,<0.19'`, so I'm currently using `python-aiorpcx 0.18.7-3`, the commit you reference is only included in 0.21.1. Is it okay to upgrade to that version or later?

**Comment by SomberNight** [comment]
No, you should not upgrade atm. e-x needs some changes first to be compatible - it was just a "note to self" kind of thing

**Comment by SomberNight** [comment]
try with master now, it uses (and requires) new aiorpcx (https://github.com/spesmilo/electrumx/commit/0256e97715f16730be7293d5f8d893bb476315dc)

**Comment by mercurytoxic** [comment]
@SomberNight Thanks for https://github.com/spesmilo/electrumx/commit/0256e97715f16730be7293d5f8d893bb476315dc that seems to have fixed the problem since I'm not  getting `AttributeError: 'NoneType' object has no attribute 'fail' ` anymore, but sadly a very similar one instaed `AttributeError: 'NoneType' object has no attribute 'host'`.

Using master at https://github.com/spesmilo/electrumx/commit/c8d2cc0d5cf9e549a90ca876d85fed9a90b8c4ed and aiorpcx at https://github.com/kyuupichan/aiorpcX/commit/e55950fed903b63e82b87c7b6ca93ab50e18ce08.

Every few seconds I get this exception: 

```
Feb 23 12:05:08 bitcoin electrumx-server[4434]: Exception in callback UVTransport._call_connection_made  
Feb 23 12:05:08 bitcoin electrumx-server[4434]: handle: <Handle UVTransport._call_connection_made>       
Feb 23 12:05:08 bitcoin electrumx-server[4434]: Traceback (most recent call last):       
Feb 23 12:05:08 bitcoin electrumx-server[4434]:   File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run    
Feb 23 12:05:08 bitcoin electrumx-server[4434]:   File "uvloop/handles/basetransport.pyx", line 145, in uvloop.loop.UVBaseTransport._call_connection_made       
Feb 23 12:05:08 bitcoin electrumx-server[4434]:   File "uvloop/handles/basetransport.pyx", line 142, in uvloop.loop.UVBaseTransport._call_connection_made       
Feb 23 12:05:08 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/aiorpcx/rawsocket.py", line 81, in connection_made  
Feb 23 12:05:08 bitcoin electrumx-server[4434]:     self.session = self.session_factory(self)  
Feb 23 12:05:08 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 947, in __init__       
Feb 23 12:05:08 bitcoin electrumx-server[4434]:     super().__init__(*args, **kwargs)    
Feb 23 12:05:08 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 876, in __init__       
Feb 23 12:05:08 bitcoin electrumx-server[4434]:     self.session_mgr.add_session(self)   
Feb 23 12:05:08 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 819, in add_session    
Feb 23 12:05:08 bitcoin electrumx-server[4434]:     self._session_group(self._ip_addr_group_name(session), 1.0),      
Feb 23 12:05:08 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 792, in _ip_addr_group_name  
Feb 23 12:05:08 bitcoin electrumx-server[4434]:     host = session.remote_address().host       
Feb 23 12:05:08 bitcoin electrumx-server[4434]: AttributeError: 'NoneType' object has no attribute 'host'       
Feb 23 12:05:15 bitcoin electrumx-server[4434]: Exception in callback UVTransport._call_connection_made  
Feb 23 12:05:15 bitcoin electrumx-server[4434]: handle: <Handle UVTransport._call_connection_made>       
Feb 23 12:05:15 bitcoin electrumx-server[4434]: Traceback (most recent call last):       
Feb 23 12:05:15 bitcoin electrumx-server[4434]:   File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run    
Feb 23 12:05:15 bitcoin electrumx-server[4434]:   File "uvloop/handles/basetransport.pyx", line 145, in uvloop.loop.UVBaseTransport._call_connection_made       
Feb 23 12:05:15 bitcoin electrumx-server[4434]:   File "uvloop/handles/basetransport.pyx", line 142, in uvloop.loop.UVBaseTransport._call_connection_made       
Feb 23 12:05:15 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/aiorpcx/rawsocket.py", line 81, in connection_made  
Feb 23 12:05:15 bitcoin electrumx-server[4434]:     self.session = self.session_factory(self)  
Feb 23 12:05:15 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 947, in __init__       
Feb 23 12:05:15 bitcoin electrumx-server[4434]:     super().__init__(*args, **kwargs)    
Feb 23 12:05:15 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 876, in __init__       
Feb 23 12:05:15 bitcoin electrumx-server[4434]:     self.session_mgr.add_session(self)   
Feb 23 12:05:15 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 819, in add_session    
Feb 23 12:05:15 bitcoin electrumx-server[4434]:     self._session_group(self._ip_addr_group_name(session), 1.0),      
Feb 23 12:05:15 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 792, in _ip_addr_group_name  
Feb 23 12:05:15 bitcoin electrumx-server[4434]:     host = session.remote_address().host       
Feb 23 12:05:15 bitcoin electrumx-server[4434]: AttributeError: 'NoneType' object has no attribute 'host'       
Feb 23 12:05:41 bitcoin electrumx-server[4434]: INFO:MemPool:compact fee histogram: [(9.7, 100474), (4.5, 125086), (3.1, 128874), (2.0, 165616), (1.1, 220154)]       
Feb 23 12:05:42 bitcoin electrumx-server[4434]: Exception in callback UVTransport._call_connection_made  
Feb 23 12:05:42 bitcoin electrumx-server[4434]: handle: <Handle UVTransport._call_connection_made>       
Feb 23 12:05:42 bitcoin electrumx-server[4434]: Traceback (most recent call last):       
Feb 23 12:05:42 bitcoin electrumx-server[4434]:   File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run    
Feb 23 12:05:42 bitcoin electrumx-server[4434]:   File "uvloop/handles/basetransport.pyx", line 145, in uvloop.loop.UVBaseTransport._call_connection_made       
Feb 23 12:05:42 bitcoin electrumx-server[4434]:   File "uvloop/handles/basetransport.pyx", line 142, in uvloop.loop.UVBaseTransport._call_connection_made       
Feb 23 12:05:42 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/aiorpcx/rawsocket.py", line 81, in connection_made  
Feb 23 12:05:42 bitcoin electrumx-server[4434]:     self.session = self.session_factory(self)  
Feb 23 12:05:42 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 947, in __init__       
Feb 23 12:05:42 bitcoin electrumx-server[4434]:     super().__init__(*args, **kwargs)    
Feb 23 12:05:42 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 876, in __init__       
Feb 23 12:05:42 bitcoin electrumx-server[4434]:     self.session_mgr.add_session(self)   
Feb 23 12:05:42 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 819, in add_session    
Feb 23 12:05:42 bitcoin electrumx-server[4434]:     self._session_group(self._ip_addr_group_name(session), 1.0),      
Feb 23 12:05:42 bitcoin electrumx-server[4434]:   File "/usr/lib/python3.10/site-packages/electrumx/server/session.py", line 792, in _ip_addr_group_name  
Feb 23 12:05:42 bitcoin electrumx-server[4434]:     host = session.remote_address().host 
```
Might this be what is slowly increasing slab allocation in vmap_area?

```
#slabtop
 Active / Total Objects (% used)    : 65711635 / 66431050 (98.9%)
 Active / Total Slabs (% used)      : 1048525 / 1048525 (100.0%)
 Active / Total Caches (% used)     : 97 / 133 (72.9%)
 Active / Total Size (% used)       : 4184377.80K / 4293098.39K (97.5%)
 Minimum / Average / Maximum Object : 0.01K / 0.06K / 8.00K

  OBJS ACTIVE  USE OBJ SIZE  SLABS OBJ/SLAB CACHE SIZE NAME
65284544 65153948  99%    0.06K 1020071       64   4080284K vmap_area
478515  86815  18%    0.05K   6555       73     26220K file_lock_ctx
141400  30092  21%    0.57K   5050       28     80800K radix_tree_node
105693 105238  99%    0.19K   5033       21     20132K kmalloc-192
```

**Comment by SomberNight** [comment]
> but sadly a very similar one instaed `AttributeError: 'NoneType' object has no attribute 'host'`.

should be fixed in https://github.com/spesmilo/electrumx/commit/25339328a7468235071d152f728b214df10d4c56

Closing this; feel free to open a new issue if there is a new trace.
