### ISSUE TITLE
AttributeError: 'TxOutput' object has no attribute 'script'

### ISSUE THREAD

**Issue by cipig** [spesmilo/electrumx#44]
BCH electrums stopped working 30 mins ago and restarting shows this error on all 3:
```
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:electrumx:ElectrumX server starting
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:electrumx:logging level: INFO
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Controller:Python version: 3.7.3 (default, Dec 20 2019, 18:57:59)  [GCC 8.3.0]
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Controller:software version: ElectrumX 1.15.0
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Controller:aiorpcX version: 0.18.4
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Controller:supported protocol versions: 1.4-1.4.2
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Controller:event loop policy: <uvloop.EventLoopPolicy object at 0x7fa7aee4b400>
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Controller:reorg limit is 200 blocks
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Daemon:daemon #1 at 127.0.0.1:33333/ (current)
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:switching current directory to /electrumdb/BCH
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:using leveldb for DB backend
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:opened UTXO DB (for sync: True)
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:UTXO DB version: 8
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:coin: BitcoinCashABC
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:network: mainnet
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:height: 645,029
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:tip: 000000000000000000527de23648977f88fe21ebe6fb97eb8f9cfc3cf1e336e1
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:tx count: 290,344,947
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:flushing DB cache at 1,200 MB
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:History:history DB version: 1
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:History:flush count: 3,217
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:DB:deleted 2,307 stale undo entries
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:SessionManager:RPC server listening on localhost:8055
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Prefetcher:catching up to daemon height 645,040 (11 blocks behind)
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:LTORBlockProcessor:chain reorg detected
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:LTORBlockProcessor:chain was reorganised replacing 1 block at heights 645,029-645,029
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:LTORBlockProcessor:read 1 blocks from disk
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Prefetcher:cancelled; prefetcher stopping
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:SessionManager:closing down server for rpc://localhost:8055
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Controller:shutting down
Jul 22 14:38:43 electrum3 electrumx_server[286753]: INFO:Controller:shutdown complete
Jul 22 14:38:43 electrum3 electrumx_server[286753]: ERROR:electrumx:ElectrumX server terminated abnormally
Jul 22 14:38:43 electrum3 electrumx_server[286753]: Traceback (most recent call last):
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/bin/electrumx_server", line 35, in main
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     asyncio.run(controller.run())
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     return loop.run_until_complete(main)
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/server_base.py", line 125, in run
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     await server_task
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/server_base.py", line 98, in serve
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     await self.serve(shutdown_event)
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/controller.py", line 134, in serve
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     await group.spawn(wait_for_catchup())
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     await self.join()
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     raise task.exception()
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 681, in fetch_and_process_blocks
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     await group.spawn(self._process_prefetched_blocks())
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     await self.join()
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     raise task.exception()
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 642, in _process_prefetched_blocks
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     await self.check_and_advance_blocks(blocks)
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 230, in check_and_advance_blocks
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     await self.reorg_chain()
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 272, in reorg_chain
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     await self.run_in_thread_with_lock(self.backup_blocks, raw_blocks)
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 202, in run_in_thread_with_lock
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     return await asyncio.shield(run_in_thread_locked())
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 201, in run_in_thread_locked
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     return await run_in_thread(func, *args)
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 68, in run_in_thread
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     return await get_event_loop().run_in_executor(None, func, *args)
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     result = self.fn(*self.args, **self.kwargs)
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 484, in backup_blocks
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     self.backup_txs(block.transactions, is_unspendable)
Jul 22 14:38:43 electrum3 electrumx_server[286753]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 835, in backup_txs
Jul 22 14:38:43 electrum3 electrumx_server[286753]:     hashX = script_hashX(txout.script)
Jul 22 14:38:43 electrum3 electrumx_server[286753]: AttributeError: 'TxOutput' object has no attribute 'script'
```

**Comment by gruve-p** [comment]
https://github.com/spesmilo/electrumx/pull/47

**Comment by FrancoBenner** [comment]
Any updates?

**Comment by SomberNight** [comment]
fixed in https://github.com/spesmilo/electrumx/pull/47
