### ISSUE TITLE
Bitcoin Cash electrumx-1.15.0 cant start, seems like reorg issue

### ISSUE THREAD

**Issue by vlddm** [spesmilo/electrumx#45]
Logs
```
INFO:DB:tip: 000000000000000000527de23648977f88fe21ebe6fb97eb8f9cfc3cf1e336e1
INFO:DB:tx count: 290,344,947
INFO:DB:flushing DB cache at 1,200 MB
INFO:History:history DB version: 0
INFO:History:flush count: 55,767
INFO:SessionManager:RPC server listening on 0.0.0.0:8000
INFO:Prefetcher:catching up to daemon height 645,042 (13 blocks behind)
INFO:LTORBlockProcessor:chain reorg detected
INFO:LTORBlockProcessor:chain was reorganised replacing 1 block at heights 645,029-645,029
INFO:LTORBlockProcessor:read 1 blocks from disk
INFO:Prefetcher:cancelled; prefetcher stopping 
INFO:LTORBlockProcessor:flushing to DB for a clean shutdown...
INFO:SessionManager:closing down server for rpc://0.0.0.0:8000
INFO:Controller:shutting down
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/home/electrumx/.local/bin/electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/lib/server_base.py", line 125, in run
    await server_task
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/lib/server_base.py", line 98, in serve
    await self.serve(shutdown_event)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/home/electrumx/.local/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/home/electrumx/.local/lib/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 681, in fetch_and_process_blocks
    await self.flush(True)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 343, in flush
    await self.run_in_thread_with_lock(flush)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 199, in run_in_thread_with_lock
    return await asyncio.shield(run_in_thread_locked())
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 198, in run_in_thread_locked
    return await run_in_thread(func, *args)
  File "/home/electrumx/.local/lib/python3.7/site-packages/aiorpcx/curio.py", line 68, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 342, in flush
    self.estimate_txs_remaining)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/db.py", line 202, in flush_dbs
    self.assert_flushed(flush_data)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/db.py", line 190, in assert_flushed
    assert flush_data.tip == self.db_tip
AssertionError
```
Same issue: https://github.com/kyuupichan/electrumx/issues/1017

**Comment by myrond** [comment]
My server got hit by this as well;  I was using the kyuupichan branch;  switched to this one.  Same problem in both.

**Comment by vlddm** [comment]
Ive removed datadase and synced from scratch, same issue again after a week
```
INFO:Prefetcher:catching up to daemon height 646,599 (51 blocks behind)
INFO:LTORBlockProcessor:chain reorg detected
INFO:LTORBlockProcessor:chain was reorganised replacing 1 block at heights 646,548-646,548
INFO:LTORBlockProcessor:read 1 blocks from disk
INFO:Prefetcher:cancelled; prefetcher stopping 
INFO:SessionManager:closing down server for rpc://0.0.0.0:8000
INFO:Controller:shutting down
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/home/electrumx/.local/bin/electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/lib/server_base.py", line 125, in run
    await server_task
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/lib/server_base.py", line 98, in serve
    await self.serve(shutdown_event)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/controller.py", line 134, in serve
    await group.spawn(wait_for_catchup())
  File "/home/electrumx/.local/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/home/electrumx/.local/lib/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 682, in fetch_and_process_blocks
    await group.spawn(self._process_prefetched_blocks())
  File "/home/electrumx/.local/lib/python3.7/site-packages/aiorpcx/curio.py", line 242, in __aexit__
    await self.join()
  File "/home/electrumx/.local/lib/python3.7/site-packages/aiorpcx/curio.py", line 211, in join
    raise task.exception()
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 643, in _process_prefetched_blocks
    await self.check_and_advance_blocks(blocks)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 230, in check_and_advance_blocks
    await self.reorg_chain()
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 272, in reorg_chain
    await self.run_in_thread_with_lock(self.backup_blocks, raw_blocks)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 202, in run_in_thread_with_lock
    return await asyncio.shield(run_in_thread_locked())
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 201, in run_in_thread_locked
    return await run_in_thread(func, *args)
  File "/home/electrumx/.local/lib/python3.7/site-packages/aiorpcx/curio.py", line 68, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 485, in backup_blocks
    self.backup_txs(block.transactions, is_unspendable)
  File "/home/electrumx/.local/lib/python3.7/site-packages/electrumx/server/block_processor.py", line 835, in backup_txs
    hashX = script_hashX(txout.script)
AttributeError: 'TxOutput' object has no attribute 'script'
```

**Comment by cipig** [comment]
same here... every little reorg will trigger this... i made a copy of the BCH DB last time it happened and using it as a starting point

**Comment by curious0101** [comment]
ElectrumX spesmilo 1.15.0 is last version with altcoin support. If there is a bug regarding your altcoin, it probably won't be fixed as altcoin support is being removed. You should move elsewhere.

**Comment by cipig** [comment]
issue was actually fixed https://github.com/spesmilo/electrumx/pull/47 and can be closed
