### ISSUE TITLE
ElectrumX dogecoin doesn't work

### ISSUE THREAD

**Issue by Turden** [spesmilo/electrumx#96]
Server crashes after synchronization with "Killed" error.

ElectrumX log:

```
INFO:electrumx:ElectrumX server starting
WARNING:Env:lowered maximum sessions from 1,000 to 674 because your open file limit is 1,024
INFO:electrumx:logging level: INFO
INFO:Controller:Python version: 3.9.1 (default, Feb  1 2021, 09:08:06)  [GCC 7.5.0]
INFO:Controller:software version: ElectrumX 1.16.0
INFO:Controller:aiorpcX version: 0.18.5
INFO:Controller:supported protocol versions: 1.4-1.4.2
INFO:Controller:event loop policy: None
INFO:Controller:reorg limit is 2,000 blocks
INFO:Daemon:daemon #1 at 127.0.0.1:22555/ (current)
INFO:DB:switching current directory to /home/ubuntu/db
INFO:DB:using leveldb for DB backend
INFO:DB:opened UTXO DB (for sync: True)
INFO:DB:UTXO DB version: 8
INFO:DB:coin: Dogecoin
INFO:DB:network: mainnet
INFO:DB:height: 3,592,619
INFO:DB:tip: d69cd535b31679cd5c505ca4ad40e5236a67a619844294af9279261bf3939e72
INFO:DB:tx count: 70,575,752
INFO:DB:flushing DB cache at 500 MB
INFO:History:history DB version: 1
INFO:History:flush count: 156
INFO:Prefetcher:catching up to daemon height 3,593,544 (925 blocks behind)
INFO:BlockProcessor:our height: 3,592,629 daemon: 3,593,544 UTXOs 0MB hist 0MB
INFO:BlockProcessor:processed 10 blocks size 0.22 MB in 2.4s
INFO:BlockProcessor:processed 700 blocks size 11.12 MB in 9.3s
INFO:BlockProcessor:processed 215 blocks size 4.27 MB in 1.5s
INFO:BlockProcessor:caught up to height 3593544
INFO:DB:flushed filesystem data in 0.01s
INFO:History:flushed history in 0.2s for 61,712 addrs
INFO:DB:flushed 925 blocks with 27,817 txs, 43,144 UTXO adds, 45,925 spends in 0.2s, committing...
INFO:DB:flush #157 took 0.5s.  Height 3,593,544 txs: 70,603,569 (+27,817)
INFO:DB:tx/sec since genesis: 6,957, since last flush: 1,845
INFO:DB:sync time: 02h 49m 07s  ETA: 00s
INFO:DB:closing DBs to re-open for serving
INFO:DB:opened UTXO DB (for sync: False)
INFO:DB:UTXO DB version: 8
INFO:DB:coin: Dogecoin
INFO:DB:network: mainnet
INFO:DB:height: 3,593,544
INFO:DB:tip: 5f5beb8d2d61f519d62a1b42fadfcf2b4814a9e53c5e8533643f536e087f0ea2
INFO:DB:tx count: 70,603,569
INFO:History:history DB version: 1
INFO:History:flush count: 157
INFO:DB:deleted 925 stale undo entries
INFO:DB:populating header merkle cache...
INFO:MemPool:beginning processing of daemon mempool.  This can take some time...
INFO:SessionManager:max session count: 674
INFO:SessionManager:session timeout: 600 seconds
INFO:SessionManager:session cost hard limit 10,000
INFO:SessionManager:session cost soft limit 1,000
INFO:SessionManager:bandwidth unit cost 5,000
INFO:SessionManager:request sleep 2,500ms
INFO:SessionManager:request timeout 30s
INFO:SessionManager:initial concurrent 10
INFO:SessionManager:max response size 10,000,000 bytes
INFO:MemPool:compact fee histogram: []
INFO:MemPool:synced in 0.28s
INFO:MemPool:182 txs 0.07 MB touching 581 addresses
INFO:SessionManager:TCP server listening on all_interfaces:50001
INFO:PeerManager:peer discovery: ON
INFO:PeerManager:announce ourself: True
INFO:PeerManager:my clearnet self: None
INFO:PeerManager:force use of proxy: False
INFO:PeerManager:beginning peer discovery...
INFO:PeerManager:trying to detect proxy on "localhost" ports [9050, 9150, 1080]
INFO:PeerManager:no proxy detected, will try later
Killed
```

ElectrumX config:
```
export DAEMON_URL=http://*:*@127.0.0.1:22555/
export DB_DIRECTORY=/home/ubuntu/db
export USERNAME=ubuntu
export COIN=Dogecoin
export NET=mainnet
export CACHE_MB=500
export SERVICES=tcp://:50001
```

Could there be a problem with setting currency in coin.py?

**Comment by amanusk** [comment]
Any success in getting it to work?

**Comment by jimtje** [comment]
Using rocksdb, my sync got caught at block 3,611,692, where it crashes trying to deserialize inputs. Although prior to that it had actually been working without issue for about 3 weeks. 

`Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:electrumx:ElectrumX server starting
Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:electrumx:logging level: INFO
Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:Controller:Python version: 3.7.9 (default, Aug 18 2020, 02:07:21)  [GCC 9.3.0]
Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:Controller:software version: ElectrumX 1.16.0
Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:Controller:aiorpcX version: 0.18.5
Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:Controller:supported protocol versions: 1.4-1.4.2
Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:Controller:event loop policy: None
Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:Controller:reorg limit is 2,000 blocks
Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:Daemon:daemon #1 at 127.0.0.1:22555/ (current)
Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:DB:switching current directory to /home/ex/db
Mar 16 16:55:20 fl electrumx_server[2062428]: INFO:DB:using rocksdb for DB backend
Mar 16 16:55:21 fl electrumx_server[2062428]: INFO:DB:opened UTXO DB (for sync: True)
Mar 16 16:55:21 fl electrumx_server[2062428]: INFO:DB:UTXO DB version: 8
Mar 16 16:55:21 fl electrumx_server[2062428]: INFO:DB:coin: Dogecoin
Mar 16 16:55:21 fl electrumx_server[2062428]: INFO:DB:network: mainnet
Mar 16 16:55:21 fl electrumx_server[2062428]: INFO:DB:height: 3,611,692
Mar 16 16:55:21 fl electrumx_server[2062428]: INFO:DB:tip: fd38f9282099649d38cbd046032f413a6db4a3d5e7e7557e73d3251336640b0a
Mar 16 16:55:21 fl electrumx_server[2062428]: INFO:DB:tx count: 71,176,859
Mar 16 16:55:21 fl electrumx_server[2062428]: INFO:DB:flushing DB cache at 2,048 MB
Mar 16 16:55:22 fl electrumx_server[2062428]: INFO:History:history DB version: 1
Mar 16 16:55:22 fl electrumx_server[2062428]: INFO:History:flush count: 14,268
Mar 16 16:55:22 fl electrumx_server[2062428]: INFO:DB:deleted 16,743 stale undo entries
Mar 16 16:55:22 fl electrumx_server[2062428]: INFO:SessionManager:RPC server listening on localhost:8000
Mar 16 16:55:22 fl electrumx_server[2062428]: INFO:Prefetcher:catching up to daemon height 3,648,553 (36,861 blocks behind)
Mar 16 16:55:23 fl electrumx_server[2062428]: INFO:Prefetcher:cancelled; prefetcher stopping
Mar 16 16:55:23 fl electrumx_server[2062428]: INFO:SessionManager:closing down server for rpc://localhost:8000
Mar 16 16:55:23 fl electrumx_server[2062428]: INFO:Controller:shutting down
Mar 16 16:55:23 fl electrumx_server[2062428]: INFO:Controller:shutdown complete
Mar 16 16:55:23 fl electrumx_server[2062428]: ERROR:electrumx:ElectrumX server terminated abnormally
Mar 16 16:55:23 fl electrumx_server[2062428]: Traceback (most recent call last):
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/bin/electrumx_server", line 35, in main
Mar 16 16:55:23 fl electrumx_server[2062428]:     asyncio.run(controller.run())
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
Mar 16 16:55:23 fl electrumx_server[2062428]:     return loop.run_until_complete(main)
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
Mar 16 16:55:23 fl electrumx_server[2062428]:     return future.result()
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/server_base.py", line 129, in run
Mar 16 16:55:23 fl electrumx_server[2062428]:     await server_task
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/server_base.py", line 102, in serve
Mar 16 16:55:23 fl electrumx_server[2062428]:     await self.serve(shutdown_event)
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/controller.py", line 134, in serve
Mar 16 16:55:23 fl electrumx_server[2062428]:     await group.spawn(wait_for_catchup())
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Mar 16 16:55:23 fl electrumx_server[2062428]:     await self.join()
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
Mar 16 16:55:23 fl electrumx_server[2062428]:     raise task.exception()
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 702, in fetch_and_process_blocks
Mar 16 16:55:23 fl electrumx_server[2062428]:     await group.spawn(self._process_prefetched_blocks())
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 242, in __aexit__
Mar 16 16:55:23 fl electrumx_server[2062428]:     await self.join()
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/aiorpcx/curio.py", line 211, in join
Mar 16 16:55:23 fl electrumx_server[2062428]:     raise task.exception()
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 663, in _process_prefetched_blocks
Mar 16 16:55:23 fl electrumx_server[2062428]:     await self.check_and_advance_blocks(blocks)
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 222, in check_and_advance_blocks
Mar 16 16:55:23 fl electrumx_server[2062428]:     for n, raw_block in enumerate(raw_blocks)]
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/server/block_processor.py", line 222, in <listcomp>
Mar 16 16:55:23 fl electrumx_server[2062428]:     for n, raw_block in enumerate(raw_blocks)]
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/coins.py", line 256, in block
Mar 16 16:55:23 fl electrumx_server[2062428]:     txs = cls.DESERIALIZER(raw_block, start=len(header)).read_tx_block()
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 152, in read_tx_block
Mar 16 16:55:23 fl electrumx_server[2062428]:     return [read() for _ in range(self._read_varint())]
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 152, in <listcomp>
Mar 16 16:55:23 fl electrumx_server[2062428]:     return [read() for _ in range(self._read_varint())]
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 142, in read_tx_and_hash
Mar 16 16:55:23 fl electrumx_server[2062428]:     return self.read_tx(), self.TX_HASH_FN(self.binary[start:self.cursor])
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 130, in read_tx
Mar 16 16:55:23 fl electrumx_server[2062428]:     self._read_inputs(),    # inputs
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 156, in _read_inputs
Mar 16 16:55:23 fl electrumx_server[2062428]:     return [read_input() for i in range(self._read_varint())]
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 156, in <listcomp>
Mar 16 16:55:23 fl electrumx_server[2062428]:     return [read_input() for i in range(self._read_varint())]
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 162, in _read_input
Mar 16 16:55:23 fl electrumx_server[2062428]:     self._read_varbytes(),   # script
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 188, in _read_varbytes
Mar 16 16:55:23 fl electrumx_server[2062428]:     return self._read_nbytes(self._read_varint())
Mar 16 16:55:23 fl electrumx_server[2062428]:   File "/usr/local/lib/python3.7/dist-packages/electrumx/lib/tx.py", line 184, in _read_nbytes
Mar 16 16:55:23 fl electrumx_server[2062428]:     assert self.binary_length >= end
Mar 16 16:55:23 fl electrumx_server[2062428]: AssertionError`

Switched to leveldb and still a few hours away from this mark. I don't know if it's the same issue - usually 'Killed' happens when RAM runs low or too many threads are being called. I'm still a few hours away from catching back up on the sync so we'll see if it works I suppose.

**Comment by amanusk** [comment]
Can confirm that solution in #99 fixed the issue for me
